[build-system]
requires = ["hatchling", "setuptools_scm>=8"]
build-backend = "hatchling.build"

[project]
name = "hyperspy_gui_anywidget"
description = "anywidget GUI elements for the HyperSpy framework."
requires-python = ">=3.10"
readme = "README.md"
keywords=[
    "data analysis",
    "microscopy",
    "anywidget",
    "hyperspy",
    "multi-dimensional",
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Topic :: Software Development :: Libraries",
  "Topic :: Scientific/Engineering",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX",
  "Operating System :: Unix",
  "Operating System :: MacOS",
]
dependencies = [
  "hyperspy>=2.3.0",
  "anywidget>=0.9.0",
  "ipywidgets>=7.6.0",
  "link_traits",
  "traitlets>=5.0",
]
version = "0.1.0"

[project.entry-points."hyperspy.extensions"]
hyperspy_gui_anywidget = "hyperspy_gui_anywidget"

[project.license]
text = "GPLv3"

[project.optional-dependencies]
tests = [
  "pytest",
  "pytest-cov",
]
doc = [
  "myst-parser",
  "pydata-sphinx-theme",
  "sphinx>=7",
]
dev = [
  "build",
  "myst-parser",
  "pre-commit",
  "ruff",
  "marimo",
  "pydata-sphinx-theme",
  "sphinx>=7",
  "towncrier>=24.8",
]

[project.urls]
"Homepage" = "https://github.com/hyperspy/hyperspy_gui_anywidget"
"Bug Reports" = "https://github.com/hyperspy/hyperspy_gui_anywidget/issues"
"Source" = "https://github.com/hyperspy/hyperspy_gui_anywidget"
"Documentation" = "https://hyperspy-gui-anywidget.readthedocs.io/"

[tool.hatch.version]
source = "literal"
build = "0.1.0"

[tool.hatch.build.targets.wheel]
packages = ["hyperspy_gui_anywidget"]
data = [
  "hyperspy_gui_anywidget/*.yaml"
]

[tool.hatch.build.targets.sdist]
include = [
  ".pre-commit-config.yaml",
  "CHANGELOG.rst",
  "CODE_OF_CONDUCT.md",
  "CONTRIBUTING.md",
  "LICENSE",
  "README.md",
  "docs",
  "hyperspy_gui_anywidget",
  "readthedocs.yaml",
  "upcoming_changes",
]

[tool.pytest.ini_options]
addopts = "-ra"
minversion = "6.0"
testpaths = [
  "hyperspy_gui_anywidget/tests",
]

[tool.coverage.run]
branch = true
source = ["hyperspy_gui_anywidget"]
omit = [
  "hyperspy_gui_anywidget/tests/*",
  "hyperspy_gui_anywidget/conftest.py",
]

[tool.coverage.report]
precision = 2
show_missing = true

[tool.ruff]
line-length = 100
force-exclude = true
extend-exclude = ["docs/_build", "examples"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[tool.towncrier]
directory = "upcoming_changes"
filename = "CHANGELOG.rst"
package = "hyperspy_gui_anywidget"
package_dir = "."
title_format = "{version} ({project_date})"
issue_format = "`#{issue} <https://github.com/hyperspy/hyperspy_gui_anywidget/issues/{issue}>`_"
start_string = ".. towncrier release notes start\n"
underlines = ["-", "~", "^"]

[[tool.towncrier.type]]
directory = "new"
name = "New features"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bug fixes"
showcontent = true

[[tool.towncrier.type]]
directory = "api"
name = "API changes"
showcontent = true

[[tool.towncrier.type]]
directory = "deprecation"
name = "Deprecations"
showcontent = true

[[tool.towncrier.type]]
directory = "doc"
name = "Documentation"
showcontent = true

[[tool.towncrier.type]]
directory = "enhancements"
name = "Enhancements"
showcontent = true

[[tool.towncrier.type]]
directory = "maintenance"
name = "Maintenance"
showcontent = true
